In [91]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Intro to tensors

Creating tensors

In [92]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [93]:
scalar.ndim

0

In [94]:
scalar.item()

7

In [95]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [96]:
vector.ndim

1

In [97]:
vector.shape

torch.Size([2])

In [98]:
#Matrix

Matrix = torch.tensor([[7,8],[7,6]])
Matrix

tensor([[7, 8],
        [7, 6]])

In [99]:
Matrix.ndim

2

In [100]:
Matrix[1]

tensor([7, 6])

In [101]:
Matrix.shape

torch.Size([2, 2])

In [102]:
#Tensor

Tensor = torch.tensor([[[1,2,3],
                       [3,4,7],
                      [2,4,9]]])

Tensor

tensor([[[1, 2, 3],
         [3, 4, 7],
         [2, 4, 9]]])

In [103]:
Tensor.ndim

3

In [104]:
Tensor.shape

torch.Size([1, 3, 3])

### random tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random number and then adjust those random numbers to better represnt the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers``

In [105]:
#Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4,)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [106]:
random_tensor.ndim

2

In [107]:
#Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels

random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

###zeros and ones

In [108]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [109]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [110]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [111]:
ones.dtype

torch.float32

###Creating a range of tensor and tensors-like

In [112]:
range1 = torch.arange(start= 0,end =1000, step=77)
range1

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [113]:
torch.__version__

'2.4.1+cu121'

In [114]:
#Creating tensors like
allzeros = torch.zeros_like(range1)
allzeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes

**Note**: tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deeep learning:
1. tensors not rigth datatype
2. Tensors not right shape
3. Tensors not on the right device

1. 32bit - torch.float
2. 64bit - torch.double
3. 16bit - torch.half

use for presion and detail

In [115]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = torch.float,
                               device=None , # what device is your tensor on
                               requires_grad = False # wheather or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [116]:
float_32_tensor.dtype

torch.float32

In [117]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [118]:
int_32_tensor = torch.tensor([3,4,5], dtype = torch.long)

In [119]:
float_32_tensor*int_32_tensor

tensor([ 9., 24., 45.])

###Getting info from tensor

1. Tensors not rigth datatype - to do get datatype from a tensor, can use `tensor.type`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [120]:
#create a tensor
some_tensor = torch.rand(3,4)

In [121]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])
Datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulation Tensors (Tensor operations)

Tensor Operations:
* Addition
* substraction
* Multiplication (element-wise)
* division
* Matrix miltiplication

In [122]:
tensor_input = torch.tensor([1,2,3,4])
print(f'add : {tensor_input + 10}')
print(f'sub : {tensor_input - 10}')
print(f'mul : {tensor_input * 10}')
print(f'add : {tensor_input + 10}')
print(f'MatMul: {torch.matmul(tensor_input,tensor_input)}')
print(f'MatMul: {tensor_input@tensor_input}')


add : tensor([11, 12, 13, 14])
sub : tensor([-9, -8, -7, -6])
mul : tensor([10, 20, 30, 40])
add : tensor([11, 12, 13, 14])
MatMul: 30
MatMul: 30


In [123]:
%%time
value = 0

for i in range(len(tensor_input)):
  value += tensor_input[i]*tensor_input[i]
print(value)

tensor(30)
CPU times: user 1.49 ms, sys: 0 ns, total: 1.49 ms
Wall time: 1.48 ms


In [124]:
%%time
torch.matmul(tensor_input,tensor_input)

CPU times: user 124 µs, sys: 23 µs, total: 147 µs
Wall time: 88 µs


tensor(30)

In [125]:
tensor_A = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B = torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

In [126]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

To fix the tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switch the axes or dim of the tensor.

In [127]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

## Finding the min, max, mean, sum , etc (tensor aggregation)

In [128]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [129]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [130]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [131]:
# torch.mean(x)

# find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work

In [132]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [133]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the postional min and max

In [134]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [135]:
# find the postion in tensor that has the min vale with argmin() -> returens index postion of target tensor where the min value occurs
x.argmin()

tensor(0)

In [136]:
x.argmax()

tensor(9)

## Reshaping, stacking , squezing and unsqueezing tensors

* Reshape - reshape an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the orginal tensor
* Stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dim to a target tensor
* permute - return a view of the input with dimension permuted (swapped) in a certain way

In [137]:
import torch
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [138]:
# add a extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [139]:
#view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [140]:
#changing z changes x (because a view of a tensor shares memory as the original)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [141]:
 # stack tensor on top of each other

 x_stack= torch.stack([x,x,x,x], dim=0)
 x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [142]:
#torch.squeeze() - remove all single dim from a target
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [143]:
x_reshaped.shape

torch.Size([1, 9])

In [144]:
x_squeezed = x_reshaped.squeeze()

In [145]:
x_reshaped.squeeze().shape

torch.Size([9])

In [146]:
# torch.unsqueeze() - adds a single dim to a target tensor at a specific dim
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [147]:
x_squeezed.shape

torch.Size([9])

In [148]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [149]:
x_unsqueezed.shape

torch.Size([1, 9])

In [150]:
# torch.permute - rearranges the dim of a target tensor in a spacified order
y = torch.rand(size=(224,224,3))
y.shape

torch.Size([224, 224, 3])

In [151]:
y_permuted = y.permute(2,0,1)

In [152]:
y[0,0,0] = 12345
y[0,0,0]

tensor(12345.)

In [153]:
y_permuted[0,0,0]

tensor(12345.)

## Indexing
indexing with pytorch is similar to indexing with numpy

In [154]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [155]:
x[:,:,1]

tensor([[2, 5, 8]])

In [156]:
# lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [157]:
# lets index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [158]:
# lets index on the most inner bracket (last dim)
x[0][2][2]

tensor(9)

In [159]:
# you can also use : to select 'all' of a target dim
x[:,0]

tensor([[1, 2, 3]])

In [160]:
# get all values of 0th and 1st dim but only index 1 of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [161]:
# get all values of the 0 dim but only the 1 index value of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [162]:
# get index 0 of 0th and 1st dim and all values of 2nd dim

In [163]:
x[0,0,:]

tensor([1, 2, 3])

In [164]:
# index on x to return 9
x



tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [165]:
x[:,2,2]

tensor([9])

## PyTorch tensor and Numpy

Numpy is a popular scientific python numerical computing library.

AND becaus of this, PyTorch has functionality ti interact with it

* Data in Numpy , want in pythorch tensor -> `torch.form_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy`

In [166]:
#numpy array to tensor
import torch
import numpy as np

array = np.arange(1.,8.)
numtensor = torch.from_numpy(array)
tensor = torch.arange(1.,8.)
array, tensor, numtensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [167]:
# change the vlaue of array , what will thus do to `tensor`?
array = array+1
array, numtensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [168]:
#Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [169]:
# change the vlaue of Tensor , what will thus do to `numpy_tensor`?
tensor = tensor+1
tensor, numpy_tensor


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility(trying to take random out of random)
In short how a neural network learns:
`start with random numbers -> tensor operations -> update random number to try and make them better representations of data -> again -> again`

To reduce the randomness in NN and PyTorch comes the concepts of a **random seed**

Essentially what the random seed does is "flavour" the randomness

In [170]:
torch.rand(3,3)

tensor([[0.5888, 0.8403, 0.4761],
        [0.7140, 0.4644, 0.6362],
        [0.8892, 0.1317, 0.7164]])

In [171]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2706, 0.6560, 0.6614, 0.3648],
        [0.1490, 0.8693, 0.0294, 0.5449],
        [0.0794, 0.2313, 0.2927, 0.3386]])
tensor([[0.3708, 0.0831, 0.0944, 0.6568],
        [0.7708, 0.1053, 0.1467, 0.1932],
        [0.9118, 0.1488, 0.0913, 0.4470]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [172]:
# lets make some random but reproducible tensor
import torch

#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA+NVIDIA hardware+PyTorch working behind the scenes to make everything hunky dory(good)

### 1. Getting a GPU

1. Easiest - google colab
2. own GPUs
3. Use cloud computing - GCP,AWS,Azure

In [173]:
# prompt: i want a code to check which gpu i am using

!nvidia-smi


Wed Oct  2 13:38:53 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P0              29W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### check for gpu access with pythorch

In [174]:
#check for gpu access woth pytorch

import torch
torch.cuda.is_available()

True

In [175]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [176]:
#Count num of devices

torch.cuda.device_count()

1

## 3. putting tensors (and models) on gpus

The Reason we want our tensors / models on the gpu is because uisng a gpu result in fatser computations.

In [177]:
#Create a tensor (default on the CPU)

tensor = torch.tensor([1,2,3], device = 'cpu')

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [178]:
#move tensor to gpu (if available )

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## 4. Moving tensors back to the cpu

In [179]:
#if tensor is on gpu, cant transform it to Numpy
# tensor_on_gpu.numpy()

In [180]:
#to fix the GPU tensor with numpy issuse , we can first set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

* https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises
* https://www.learnpytorch.io/00_pytorch_fundamentals/#extra-curriculum